server:
  port: 8190
spring:
  datasource:
    url: jdbc:h2:mem:clients-db;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  data:
    jdbc:
      dialect: h2