server:
    port: 8191
spring:
    application:
        name: java-pro-spring
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        driver-class-name: org.postgresql.Driver
        username: admin
        password: admin
    jpa:
        show-sql: true
    data:
        jdbc:
            dialect: postgresql
limits-service:
    limit:
        init-value: 10000.00

